---
version: '3.8'
services:
  # Portainer Docker Management
  portainer:
    container_name: portainer
    image: portainer/portainer
    hostname: portainer
    restart: unless-stopped
    environment:
      - SESSION_TIMEOUT=315360000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    networks:
      - services
    deploy:
      resources:
        limits:
          memory: 64M
  nginx:
    container_name: nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - nginx-data:/data
      - nginx-certs:/etc/letsencrypt
    networks:
      - services
  db:
    container_name: db
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - nginx-db:/var/lib/mysql
    networks:
      - services
  dashy:
    container_name: dashy
    image: 'lissy93/dashy:latest'
    restart: unless-stopped
    volumes:
      - $VOLUME_PATH/dashy/public/conf.yml:/app/public/conf.yml
      - dashy-icons:/app/public/item-icons/icons
    networks:
      - services
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: ./jenkins/jenkins_dockerfile
    image: jenkins:built
    restart: unless-stopped
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    depends_on:
      - jenkins_bind
    networks:
      - services
  jenkins_bind:
    container_name: bind_jenkins
    build:
      context: .
      dockerfile: ./jenkins/jenkins_bind_dockerfile
    image: jenkins_bind:built
    restart: unless-stopped
    privileged: true
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      services:
        aliases:
          - docker

# Docker Networks
networks:
  services:
    driver: bridge

# Docker Volumes
volumes:
  portainer-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$VOLUME_PATH/portainer/portainer_data'
  nginx-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$VOLUME_PATH/nginx/nginx_data'
  nginx-db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$VOLUME_PATH/nginx/nginx_db'
  nginx-certs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$VOLUME_PATH/nginx/nginx_certs'
  dashy-icons:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$VOLUME_PATH/dashy/icons'
  jenkins-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$VOLUME_PATH/jenkins/data'
  jenkins-docker-certs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$VOLUME_PATH/jenkins/certs'