---
version: '3.8'
services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: ./jenkins_dockerfile
    image: jenkins:built
    restart: unless-stopped
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    depends_on:
      - jenkins_bind
    ports:
      - 8080:8080
      - 5000:5000
    networks:
      - services
  jenkins_bind:
    container_name: bind_jenkins
    build:
      context: .
      dockerfile: ./jenkins_bind_dockerfile
    image: jenkins_bind:built
    restart: unless-stopped
    privileged: true
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - 2376:2376
    networks:
      services:
        aliases:
          - docker

# Docker Networks
networks:
  services:
    driver: bridge

# Docker Volumes
volumes:
  jenkins-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$VOLUME_PATH/jenkins/data'
  jenkins-docker-certs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$VOLUME_PATH/jenkins/certs'