---
version: '3.8'
services:
  # Jenkins Server
  jenkins-server:
    container_name: jenkins_server
    build:
      context: .
      dockerfile: ./jenkins/jenkins_server
    image: jenkins:built
    restart: unless-stopped
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    depends_on:
      - jenkins-docker-in-docker
    networks:
      - services

  # Jenkins Docker In Docker
  jenkins-docker-in-docker:
    container_name: jenkins_dind
    build:
      context: .
      dockerfile: ./jenkins/jenkins_dind
    image: jenkins_dind:built
    restart: unless-stopped
    privileged: true
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      services:
        aliases:
          - docker

# Docker Networks
networks:
  services:
    driver: bridge

# Docker Volumes
volumes:
  jenkins-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$VOLUME_PATH/jenkins/data'
  jenkins-docker-certs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$VOLUME_PATH/jenkins/certs'