---
- Hypervisors:
    - Proxmox-Home-PVE1:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_HOME_PVE1_PROXMOX_URL}}"
        description: "{{HOMEPAGE_VAR_HOME_PVE1_PROXMOX_DESCRIPTION}}"
        widget:
            type: proxmox
            url: "{{HOMEPAGE_VAR_HOME_PVE1_PROXMOX_URL}}"
            username: "{{HOMEPAGE_VAR_HOME_PVE1_PROXMOX_USER}}"
            password: "{{HOMEPAGE_VAR_HOME_PVE1_PROXMOX_API_KEY}}"
            node: "{{HOMEPAGE_VAR_HOME_PVE1_PROXMOX_NODE}}"

    - Proxmox-Work-PVE1:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_WORK_PVE1_PROXMOX_URL}}"
        description: "{{HOMEPAGE_VAR_WORK_PVE1_PROXMOX_DESCRIPTION}}"
        widget:
            type: proxmox
            url: "{{HOMEPAGE_VAR_WORK_PVE1_PROXMOX_URL}}"
            username: "{{HOMEPAGE_VAR_WORK_PVE1_PROXMOX_USER}}"
            password: "{{HOMEPAGE_VAR_WORK_PVE1_PROXMOX_API_KEY}}"
            node: "{{HOMEPAGE_VAR_WORK_PVE1_PROXMOX_NODE}}"

    - Proxmox-Work-PVE2:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_WORK_PVE2_PROXMOX_URL}}"
        description: "{{HOMEPAGE_VAR_WORK_PVE2_PROXMOX_DESCRIPTION}}"
        widget:
            type: proxmox
            url: "{{HOMEPAGE_VAR_WORK_PVE2_PROXMOX_URL}}"
            username:  "{{HOMEPAGE_VAR_WORK_PVE2_PROXMOX_USER}}"
            password:  "{{HOMEPAGE_VAR_WORK_PVE2_PROXMOX_API_KEY}}"
            node: "{{HOMEPAGE_VAR_WORK_PVE2_PROXMOX_NODE}}"

    - Proxmox-Work-PVE3:
        icon: proxmox.svg
        href: "{{HOMEPAGE_VAR_WORK_PVE3_PROXMOX_URL}}"
        description: "{{HOMEPAGE_VAR_WORK_PVE3_PROXMOX_DESCRIPTION}}"
        widget:
            type: proxmox
            url: "{{HOMEPAGE_VAR_WORK_PVE3_PROXMOX_URL}}"
            username: "{{HOMEPAGE_VAR_WORK_PVE3_PROXMOX_USER}}"
            password: "{{HOMEPAGE_VAR_WORK_PVE3_PROXMOX_API_KEY}}"
            node: "{{HOMEPAGE_VAR_WORK_PVE3_PROXMOX_NODE}}"

# - Containers:
    # - Rancher:
    #     icon: rancher.svg
    #     href: "{{HOMEPAGE_VAR_RACNHER_URL}}"
    #     description: "{{HOMEPAGE_VAR_RACNHER_DESCRIPTION}}"
    # - Longhorn:
    #     icon: longhorn.svg
    #     href: "{{HOMEPAGE_VAR_LONGHORN_URL}}"
    #     description: "{{HOMEPAGE_VAR_LONGHORN_DESCRIPTION}}"

- DNS:
    - Pi-Hole1:
        icon: pi-hole.svg
        href: "{{HOMEPAGE_VAR_PIHOLE1_URL}}/admin/"
        description: "{{HOMEPAGE_VAR_PIHOLE1_DESCRIPTION}}"
        widget:
            type: pihole
            url: "{{HOMEPAGE_VAR_PIHOLE1_URL}}"
            key: "{{HOMEPAGE_VAR_PIHOLE1_API_KEY}}"

- Network:
    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
        description: internal
        widget:
            type: uptimekuma
            url: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
            slug: home

    - Nginx Proxy Manager Home:
        icon: nginx-proxy-manager.svg
        href: "{{HOMEPAGE_VAR_HOME_NGINX_PROXY_MANAGER_URL}}"
        description: "{{HOMEPAGE_VAR_HOME_NGINX_PROXY_MANAGER_DESCRIPTION}}"
        widget:
            type: npm
            url: "{{HOMEPAGE_VAR_HOME_NGINX_PROXY_MANAGER_URL}}"
            username: "{{HOMEPAGE_VAR_HOME_NGINX_PROXY_MANAGER_USERNAME}}"
            password: "{{HOMEPAGE_VAR_HOME_NGINX_PROXY_MANAGER_PASSWORD}}"

    - Nginx Proxy Manager Work:
        icon: nginx-proxy-manager.svg
        href: "{{HOMEPAGE_VAR_WORK_NGINX_PROXY_MANAGER_URL}}"
        description: "{{HOMEPAGE_VAR_WORK_NGINX_PROXY_MANAGER_DESCRIPTION}}"
        widget:
            type: npm
            url: "{{HOMEPAGE_VAR_WORK_NGINX_PROXY_MANAGER_URL}}"
            username: "{{HOMEPAGE_VAR_WORK_NGINX_PROXY_MANAGER_USERNAME}}"
            password: "{{HOMEPAGE_VAR_WORK_NGINX_PROXY_MANAGER_PASSWORD}}"

- Storage:
    - TrueNAS-Home:
        icon: truenas.svg
        href: "{{HOMEPAGE_VAR_HOME_TRUENAS_URL}}"
        description: "{{HOMEPAGE_VAR_HOME_TRUENAS_DESCRIPTION}}"
        widget:
            type: truenas
            url: "{{HOMEPAGE_VAR_HOME_TRUENAS_URL}}"
            key: "{{HOMEPAGE_VAR_HOME_TRUENAS_API_KEY}}"

    - TrueNAS-Work:
        icon: truenas.svg
        href: "{{HOMEPAGE_VAR_WORK_TRUENAS_URL}}"
        description: "{{HOMEPAGE_VAR_WORK_TRUENAS_DESCRIPTION}}"
        widget:
            type: truenas
            url: "{{HOMEPAGE_VAR_WORK_TRUENAS_URL}}"
            key: "{{HOMEPAGE_VAR_WORK_TRUENAS_API_KEY}}"

    - File Browser:
        icon: filebrowser.svg
        href: "{{HOMEPAGE_VAR_FILE_BROWSER_URL}}"
        description: "{{HOMEPAGE_VAR_FILE_BROWSER_DESCRIPTION}}"

- Media:
    - NextCloud:
        icon: nextcloud.svg
        href: "{{HOMEPAGE_VAR_NEXTCLOUD_URL}}"
        description: "{{HOMEPAGE_VAR_NEXTCLOUD_DESCRIPTION}}"
        widget:
            type: nextcloud
            url: "{{HOMEPAGE_VAR_NEXTCLOUD_URL}}"
            username: "{{HOMEPAGE_VAR_NEXTCLOUD_USERNAME}}"
            password: "{{HOMEPAGE_VAR_NEXTCLOUD_PASSWORD}}"

- Other:
    - GitLab:
        icon: gitlab.svg
        href: https://gitlab.com
        description: source code
    - GitHub:
        icon: github.svg
        href: https://github.com
        description: source code
    - Shlink:
        icon: https://shlink.io/images/shlink-logo-blue.svg
        href: "{{HOMEPAGE_VAR_SHLINK_URL}}"
        description: dashboard
