---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Joker Wrld Homepage

background:
  image: https://cdnb.artstation.com/p/assets/images/images/060/534/953/medium/julia-gorokhova-sci-fi-alley-fin2.jpg?1678790506
  blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100

theme: dark
color: slate

# useEqualHeights: true

layout:
  Hypervisors:
    header: true
    style: row
    columns: 4
  Containers:
    header: true
    style: row
    columns: 4
  DNS:
    header: true
    style: row
    columns: 4
  Network:
    header: true
    style: row
    columns: 4
  Storage:
    header: true
    style: row
    columns: 4
  Media:
    header: true
    style: row
    columns: 4
  Other:
    header: true
    style: row
    columns: 4

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey